### ISSUE TITLE
White text background in “Back to top” component is visually unappealing

### ISSUE THREAD

**Issue by lewisdorigo** [scottish-government-design-system/design-system#149]
The “Back to top” is a padded block which has a semi-transparent background (`rgba(255, 255, 255, .4)`).

There is additional styling applied to the `::before` pseudo-element, as well as the `.ds_back-to-top__icon` element to apply a solid white background behind the text.

I think this implementation is quite visually unappealing and — to me — makes the component look confusing, when there are patterns behind the component.

For example, this is how the component looks on the [Design System’s website](https://designsystem.gov.scot) on a mobile device:

![Image](https://github.com/user-attachments/assets/8f158f24-7933-4a8a-b8ff-e3804d5c006a)

I completely understand the need to ensure that there is enough contrast between the background and the text, and applying this white background is there to ensure that. However, I think there are probably better ways to ensure this contrast.

Simply using a solid white background on the entire component would be the simplest solution.

If we don’t want to entirely obscure the background, the `backdrop-filter` property could be used (alongside a fallback), alongside a more opaque background to allow some of the background to filter through while still maintaining contrast.

E.g.:
```scss
.ds_back-to-top__button {
    background: #fff;
    
    @supports (backdrop-filter: blur(5px)) {
        background: rgba(255,255,255,.85);
        backdrop-filter: blur(5px);
    }
}
```

Which would result in:
![Image](https://github.com/user-attachments/assets/07b18618-635c-4c1c-9827-6572da5ebd6f)

In this example, the contrast between the bluest portion of the background and the text is 4.9, which achieves the contrast required for compliance with Level AA.
